### ISSUE TITLE
map does not actually achieve any parallelism

### ISSUE THREAD

**Issue by bernstei** [Helveg/zwembad#10]
The calls to `result()` that occur inside the list comprehension that `map()` uses to call `submit()` prevents parallelism, from what I can tell.  If, instead, the list comprehension just stores the futures returned by `submit()`, and then a second list comprehension calls `result()` for each of them, the tasks appear to really get done in parallel.  However, since I don't quite understand the full structure of the package, I'm not sure if this is the right solution, or if it could lead to a deadlock, for example.

**Comment by bernstei** [comment]
Note that I'm seeing situations where this is not sufficient, but still investigating the details.

**Comment by bernstei** [comment]
OK - the problem is specific to how we have structured the iterables that we're passing to the `map` call.  I don't understand why, but the loop over the iterable hangs.  The iterable is an object with an `__iter__` method, so it's somewhat complex.  I can't figure out where the hang happens - at least based on adding print statements, it's apparently not in the loop that calls submit, nor is it in the __iter__ method of the iterable object.

Obviously we're checked that the iterable itself it OK - iterating without the submit calls works fine.

**Comment by bernstei** [comment]
never mind my earlier comments, now deleted - that was basically just a bug in my code.

**Comment by Helveg** [comment]
Oh wow yea, I wrote map under the following assumptions, but my test script indeed showed there's a bug in the parallelism

> For each future that you get back from `pool.submit()` a different thread has been started. The thread starts a blocking MPI read operation to the worker. What `map` does is just wait for all these parallel threads on the master to collect their results from the workers.

> (Whenever a worker is done and the result collected on the job thread, the worker is "handed over" to the next item on the queue of the pool)

**Comment by Helveg** [comment]
I will fix this asap (sorry I only used `submit` myself ;p )

**Comment by Helveg** [comment]
The problem was that I was creating a future and immediately waiting for its result, while I should first submit all the futures and only afterwards start waiting for them.

It's fixed in v1.2.2 (and v1.2.2.dev0 for Py3.6). Thanks for this report!

**Comment by bernstei** [comment]
On Mar 9, 2021, at 12:23 PM, Robin De Schepper <notifications@github.com<mailto:notifications@github.com>> wrote:

The problem was that I was creating a future and immediately waiting for its result, while I should first make all the futures and only then start waiting for them. It's fixed in v1.2.2, I'll make another v3.6 version for you ^_^

Thanks.  The 3.6 branch version of pool.py still has the / in the declaration of submit().  Is that intentional?  Because that's not actually supported in 3.6.

Noam

**Comment by Helveg** [comment]
That was unintentional, must've slipped through, I corrected it in `1.2.2.dev1`

**Comment by bernstei** [comment]
On Mar 9, 2021, at 3:27 PM, Robin De Schepper <notifications@github.com<mailto:notifications@github.com>> wrote:



That was unintentional, must've slipped through, I corrected it in 1.2.2.dev1

Thanks.

Noam


____________
|
|
|
U.S. NAVAL
|
|
_RESEARCH_
|
LABORATORY

Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil
