### ISSUE TITLE
Dealing with workers

### ISSUE THREAD

**Issue by AliceGem** [Helveg/zwembad#11]
```
from zwembad import MPIPoolExecutor as Pool
from deap import base

# Initialize toolbox and MPI pool
toolbox = base.Toolbox()

with Pool() as pool:
  pool.workers_exit()
  toolbox.register("map", pool.map)
```
If I run this locally with MPI it runs correctly; on Piz Daint I get the following error:

> Traceback (most recent call last):
>   File "test_mpi_pool_optim.py", line 50, in <module>
>     pool.workers_exit()
> AttributeError: 'MPIPoolExecutor' object has no attribute 'workers_exit'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_mpi_pool_optim.py", line 51, in <module>
>     toolbox.register("map", pool.map)
>   File "/opt/python/3.8.2.1/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
>     self.shutdown(wait=True)
> TypeError: shutdown() got an unexpected keyword argument 'wait'

**Comment by Helveg** [comment]
If this problem persists in `mpipool>=1.0.0` (soon to be released) please open an issue on https://github.com/mpipool/mpipool

**Comment by AliceGem** [comment]
Should I go back to mpipool?
