### ISSUE TITLE
Add a `rejoin=False` option

### ISSUE THREAD

**Issue by Helveg** [Helveg/zwembad#9]
Add the option for a `Pool` to keep the workers in the worker loop until shutdown:

```python
pool = Pool(rejoin=False)
# The workers never rejoin the code so you can do whatever here
pool.map(...)
pool.shutdown()
```

A 2nd `pool = Pool()` would fail since the worker MPI processes have already shut down.

**Comment by bernstei** [comment]
Responding to #7 here, yes, I think this would be helpful for my use case.

**Comment by Helveg** [comment]
Added in [`mpipool==1.0.0`](https://github.com/mpipool/mpipool).
